version: "3"

services:
  web:
    build: .
    command: python3 app.py
    container_name: web
    ports:
      - "5000:5000"
#    volumes:
#      - .:/srv
#    links:
#     - redis
    networks:
      - redisnet
  redis:
    image: redis:alpine
    container_name: redis
    networks:
      - redisnet

networks:
  redisnet:
    name: redisnet
